# Generated by Django 5.2.9 on 2026-01-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChronasAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
