# Generated by Django 6.0 on 2026-03-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChronasAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
