# Generated by Django 6.0 on 2026-03-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChronasAdmin', '0002_alter_product_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subdescription',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='FineArtSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='ChronasAdmin.product')),
            ],
        ),
    ]
