# Generated by Django 6.0 on 2026-03-18 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChronasAdmin', '0005_frame_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChronasAdmin.frame'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChronasAdmin.material'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChronasAdmin.fineartsize'),
        ),
        migrations.AddField(
            model_name='product',
            name='frames',
            field=models.ManyToManyField(blank=True, related_name='products', to='ChronasAdmin.frame'),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='products', to='ChronasAdmin.material'),
        ),
    ]
