# Generated by Django 6.0 on 2026-05-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChronasAdmin', '0006_orderitem_frame_orderitem_material_orderitem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
