# Generated by Django 6.0 on 2026-02-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChronasAdmin', '0003_order_email_order_guest_id_order_payment_id_and_more'),
        ('ChronasAdmin', '0007_alter_product_image'),
    ]

    operations = [
    ]
