# Generated by Django 6.0 on 2026-06-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChronasAdmin', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10, unique=True)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
