# Generated by Django 6.0 on 2026-06-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChronasAdmin', '0010_exchangerate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
