# Generated by Django 6.0 on 2026-07-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChronasAdmin', '0015_supplier_address_supplier_country_supplier_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
