# Generated by Django 6.0 on 2026-07-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChronasAdmin', '0017_remove_product_sku_productvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('fine_art', 'Fine Art'), ('variant', 'Variant Product')], default='variant', max_length=20),
        ),
    ]
