# Generated by Django 6.0 on 2026-07-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChronasAdmin', '0019_productvariant_created_at_productvariant_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='updated_at',
        ),
    ]
