# Generated by Django 6.0 on 2026-07-16 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChronasAdmin', '0020_remove_productvariant_created_at_and_more'),
        ('ChronusUser', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='ChronasAdmin.productvariant'),
        ),
    ]
